### ISSUE TITLE
parseToJSON should check for closing tags

### ISSUE THREAD

**Issue by mstachowsky** [mstachowsky/Klein-Clientside#15]
The javascript engine won't render a JSON book unless it is perfectly formatted.  Hand-editing markdown code sometimes leads to closing tags being forgotten (most common is !endPage).  parseToJSON should handle this.  Use a stack-based algorithm.

**Comment by NotCalvinLu** [comment]
Made stack based function for tag matching, has been pushed to my branch - kevin_testing. Added error message when matching fails, shows last stack push.
