### ISSUE TITLE
Create !algorithm directive and/or algorithm file

### ISSUE THREAD

**Issue by mstachowsky** [mstachowsky/Klein-Clientside#24]
Random variables is a good start.  However, it would be very useful to be able to define variables with expressions like this:

!var x:1:10:1
!var y:1:10:1
!var z = x+y

I do not have an objection to keeping the !randVar directive to create random variables.  It's also OK to have a !variables directive to declare non-random variables.  No matter what, we should have an !algorithm directive that allows us to assign values to variables based on expressions that include numeric constants and other variables.  These expressions can just be pure javascript code.

This functionality already exists for answer boxes, in that an algorithm can be written directly.  That's good and should be kept.  However, being able to define variables in an algorithm environment AS WELL would allow us to create complex, multi-part questions

**Comment by NotCalvinLu** [comment]
can now use embedded command -> eqn:( some math , unique variable name) to render value and store as a variable or just eqn:( some math) to just render the value

**Comment by NotCalvinLu** [comment]
Following can now be done.
!bookVariables

	!var %x:1:10:2
	!var %y:10:100:3
	!var %test: %x + %y

!endBookVariables
