### ISSUE TITLE
Store answers for use in other questions

### ISSUE THREAD

**Issue by mstachowsky** [mstachowsky/Klein-Clientside#25]
Sometimes, design problems have more unknowns than equations.  We should be able to define algorithms in terms of the answers stored in the answer box.  For example, assume that we have an equation:

V1 = R1/(R1+R2)

Where V1 is what we are looking for in one answer box, and R1 and R2 come from two other answer boxes.  V1's answer box should be able to access R1 and R2 and should automatically update upon clicking "how did I do".

**Comment by NotCalvinLu** [comment]
can now use embedded command -> eqn:( some math , unique variable name) to render value and store as a variable or just eqn:( some math) to just render the value
