### ISSUE TITLE
Easy setup for books on server

### ISSUE THREAD

**Issue by mstachowsky** [mstachowsky/Klein-Clientside#29]
Currently, setting up a book on the server is a laborious process of making a new folder, making the appropriate subfolders, creating the HTML files and putting it in the right place.  It would be great if we could make scripts for both Linux and Windows that receive a book name and set up the appropriate folder structures in the appropriate root directories.

**Comment by lemonnuggets** [comment]
This seems like something I could help out with. Could you please detail what the folder structure would look like and how you would want the script integrated into this project?

**Comment by mstachowsky** [comment]
Sounds good!  I'm going to give you a lot more information than you may need, since I'm also thinking this through a bit in my head.  Hopefully it isn't too much:

There are two major folders that need to be created: the book's development folder and the book folder itself.  These can be stored at different roots, so let's call the root folders devRoot and bookRoot.  There is another path we need to specify, scriptPath, which contains a path to relevant parsing scripts.  I suggest making some kind of config file that contains these three paths that the user can edit once, then your script uses that file.

**Book Development Folder**: This is a single folder whose name is the name of the book with the string "_dev" appended to the end.  It contains no subfolders, but there is a mandatory file called "parse" and the book file itself.  See below for more info.  If our book is called "book1", then when we run your script we should get a folder called "book1_dev" at location devRoot/book1_dev.

**Book folder**: The book folder lives in bookRoot and it must have the name of the book only.  So to continue our example with "book1", it must be placed at bookRoot/book1.  It contains a subfolder, "res", placed at bookRoot/book1/res.  Upon creation the book folder itself should not contain any files, but res should contain the html file (see below).

**Ideal case: Mandatory files are also created** I'll leave this to you if you want to create a new issue and solve it later or solve this all at once.  The development folder should contain the book file itself and a "parse" script.  

The parse script:  Here is an example of a parse script.  I've edited out my actual bookRoot path and replaced it with just bookRoot.  This is done in MS Windows, but I'd like to see both a Linux and Windows version when this issue is closed:

`@ECHO OFF
python [scriptPath]/parseToJSON.py /book1
move *.bk [bookRoot]/book1`

The book file is a lot simpler.  It's a markdown file with extension .md that should just contain a single line of text:  !Book book1

where "book1" needs to be replaced with the name of the book we are making.

Finally, the HTML file that is placed in the "res" folder should be a near copy of the file "LectureReviews.html", except the text in line 35 (starting with let url=) needs to be modified to point to the correct book file.  In this case, rather than the path on my system, it should be `[bookRoot]/book1/book1.bk`

**Comment by lemonnuggets** [comment]
Okay, I think I have a decent idea of what you're looking for now. Thanks for the extremely thorough description. So if I understand right I can add my script in the root directory of the project, where `parseToJSON.py` is right?

**Comment by mstachowsky** [comment]
yes, that would be fine.

**Comment by lemonnuggets** [comment]
Great I'll get started on it. I'll get back to you if I have any more doubts.
