### ISSUE TITLE
Investigate and advise on various open-source licences to apply to this project

### ISSUE THREAD

**Issue by mstachowsky** [mstachowsky/Klein-Clientside#35]
Klein is currently provided using the Beer license, but I'd prefer it to have a more formal license.  However, I don't know enough about open-source licensing to make this decision.  Advice would be helpful.

**Comment by mau-p** [comment]
Hi @mstachowsky, I came across your issue, and this is for me a first issue. While I am no expert whatsoever at open-source licensing, I did try my best to look it up.
Basically, certain frameworks like wordpress, apache or OpenBSD require a specific license. However, that doesn't seem to be the case here. 
The 2 main licenses for open source software are MIT and GNU GPLv3. 
MIT is the most permissive, it lets people do whatever they want with the project. This includes forking it, making it closed source and selling it. This is the closest with what you currently have, except they're not even expected to give you a beer if you meet :smile: 
GNU GPLv3 on the other hand still lets people fork it and do whatever they want, so they can still sell it, but it prohibits anyone from making it closed source. GIMP uses the GNU GPLv3 license, and the Linux kernel uses the GNU GPLv2 license. Overall, GNU GPLv3 is considered an improvement other GNU GPLv2. It mostly tries to clarify some points, fix some loopholes. It also prevents the project from included in technology or products that would be used to enforce the Digital Millennium Copyright Act.

I hope to have given you some clarity to these licenses.

**Comment by mau-p** [comment]
I created a pull request with the license.  I included the standard GNU GPLv3 template that github provides. As far as I can tell this is an upgrade from a informal beer license. Keep in mind that you can always change the license if you don't think this one suits the project.
