### ISSUE TITLE
Add license comments to all code files

### ISSUE THREAD

**Issue by mstachowsky** [mstachowsky/Klein-Clientside#39]
Add the following blurb in a block-comment to all code files, regardless of language:

  @license
 
  Licensed under the GNU GPLv3 License (the "License"); you may not
  use this file except in compliance with the License. You may obtain a copy
  of the License at
 
  https://www.gnu.org/licenses/gpl-3.0.en.html
 
  Any libraries written by third parties are provided under a license that is identical to or compatible with the License on this project.
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations under
  the License.

**Comment by glaukiol1** [comment]
@mstachowsky, Im going to work on this!
