### ISSUE TITLE
Change the height of the header

### ISSUE THREAD

**Issue by mstachowsky** [mstachowsky/Klein-Clientside#6]
Currently the header is a fixed height.  However, if the text is too long for that height it will word wrap over the header and onto the stuff below.  Setting its min-height means that the header will grow, but then it will grow into the content.  We need to ensure that the content is moved down to the bottom of the header.

**Comment by NotCalvinLu** [comment]
Fix the overlapping heading, sidebar and content now moves down based on heading length. Sidebar buttons have similar issue if the button label is too long. This may be ignorable.
