### ISSUE TITLE
Create a book from page files

### ISSUE THREAD

**Issue by mstachowsky** [mstachowsky/Klein-Clientside#9]
Currently we are writing the entire book on a single document.  This will get cumbersome and make it hard to share stuff.  It should be possible to write pages on separate files and then include them into a book document if desired.  This should be optional - we should still be able to parse an entire book.

I recommend using a pre-processor program that combines a number of different important functionalities (like pages, but also algorithms etc) that runs before and creates the book markdown file.  If there is nothing to pre-process this program should do nothing and just pass it along to parseToJSON.py, which turns it into JSON.

**Comment by NotCalvinLu** [comment]
Functionality added to parsetoJSON.py on my branch kevin_testing
